name: Push to Stoplight

on: [push]

jobs:
  push-to-stoplight:
      name: Push to Stoplight
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Push to Stoplight
          run: |
            npx @stoplight/cli@6 push --ci-token ${{ env.STOPLIGHT_CI_TOKEN }}
          env: 
            # Get the CI token from project settings on your Stoplight workspace
            # Go to https://{workspace}.stoplight.io/settings/{project}/automation
            # Relevant docs: https://meta.stoplight.io/docs/platform/f76c84240244f-publish-with-the-stoplight-cli#continuous-integration
            STOPLIGHT_CI_TOKEN: ${{ secrets.STOPLIGHT_CI_TOKEN }}